"""
Extraction module for Meta Ads spend data.

In production this would call the Meta Marketing API. In this project it reads
the synthetic CSV generated by seed_data.py, giving Dagster a clean abstraction
to wrap: swap the CSV read for a real API call without changing the Dagster asset.
"""

import os
import pandas as pd
from pathlib import Path
from typing import Optional

DATA_DIR = Path(os.environ.get("DATA_DIR", "/workspace/data"))


def extract_meta_ads() -> pd.DataFrame:
    """Return raw Meta Ads spend as a DataFrame with canonical column names."""
    csv_path = DATA_DIR / "meta_ads_raw.csv"
    if not csv_path.exists():
        raise FileNotFoundError(
            f"Meta Ads CSV not found at {csv_path}. Run seed_data.py first."
        )
    df = pd.read_csv(csv_path, parse_dates=["date"])
    return df


if __name__ == "__main__":
    df = extract_meta_ads()
    print(f"Meta Ads: {len(df)} rows | {df['campaign_id'].nunique()} campaigns")
    print(df.dtypes)
    print(df.head(3))
