import os
from pathlib import Path
from dagster import AssetExecutionContext
from dagster_dbt import DbtCliResource, dbt_assets

DBT_PROJECT_DIR = Path(os.environ.get("DBT_PROJECT_DIR", "/workspace/dbt_project"))

# The manifest is generated by `dbt parse` or `dbt compile` before Dagster starts.
# Each dbt model becomes a Dagster asset — lineage from raw → bronze → silver → gold
# is inferred automatically from the dbt ref() and source() calls.
@dbt_assets(manifest=DBT_PROJECT_DIR / "target" / "manifest.json")
def onboarding_dbt_assets(context: AssetExecutionContext, dbt: DbtCliResource):
    yield from dbt.cli(["build"], context=context).stream()
